-- sqldevloper 에서 생성 필요(계정이름 cap 기준)
-- qw, qwe, qwer 계정(비번 모두 qw) 및 다수의 주차장/충전소 요청 데이터 포함
--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-11-2020
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CS
--------------------------------------------------------

  CREATE TABLE "CAP"."CS"
   (	"CHARGENAME" VARCHAR2(50 BYTE),
	"OPERATION" VARCHAR2(100 BYTE),
	"CHARGESPEED" VARCHAR2(50 BYTE),
	"CHARGEAMOUNT" VARCHAR2(50 BYTE),
	"MIN30FEE" VARCHAR2(100 BYTE),
	"ADDMIN10FEE" VARCHAR2(100 BYTE),
	"MANAGETIME" VARCHAR2(30 BYTE),
	"CHARGEPIC" VARCHAR2(2000 BYTE),
	"APTMAP" VARCHAR2(2000 BYTE),
	"CABLE" VARCHAR2(50 BYTE),
	"CHARGETYPE" VARCHAR2(50 BYTE),
	"REGDATE" TIMESTAMP (6),
	"CHARGINGCHK" VARCHAR2(1 BYTE) DEFAULT 'N',
	"RESNAME" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GUARD
--------------------------------------------------------

  CREATE TABLE "CAP"."GUARD"
   (	"EMAIL" VARCHAR2(100 BYTE),
	"GUARDLICENCE" VARCHAR2(2000 BYTE),
	"GUARDCO" VARCHAR2(100 BYTE),
	"GUARDCONUM" VARCHAR2(20 BYTE),
	"REGDATE" TIMESTAMP (6),
	"RESNAME" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "CAP"."MEMBER"
   (	"EMAIL" VARCHAR2(100 BYTE),
	"CREATED_DATE" TIMESTAMP (6),
	"MODIFIED_DATE" TIMESTAMP (6),
	"NAME" VARCHAR2(30 BYTE),
	"PASSWORD" VARCHAR2(100 BYTE),
	"PHONE" VARCHAR2(20 BYTE),
	"PICTURE" VARCHAR2(1000 BYTE),
	"ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKING
--------------------------------------------------------

  CREATE TABLE "CAP"."PARKING"
   (	"PARKINGNAME" VARCHAR2(300 BYTE),
	"PARKINGTYPE" VARCHAR2(30 BYTE),
	"PLACE" NUMBER,
	"MIN30FEE" NUMBER,
	"ADDMIN10FEE" NUMBER,
	"MANAGETIME" VARCHAR2(30 BYTE),
	"PARKINGPIC" VARCHAR2(2000 BYTE),
	"APTMAP" VARCHAR2(2000 BYTE),
	"REGDATE" TIMESTAMP (6),
	"PARKINGCHK" VARCHAR2(1 BYTE) DEFAULT 'N',
	"RESNAME" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKINGBOOK
--------------------------------------------------------

  CREATE TABLE "CAP"."PARKINGBOOK"
   (	"BOOKID" VARCHAR2(100 BYTE),
	"STARTDATE" TIMESTAMP (6),
	"ENDDATE" TIMESTAMP (6),
	"PAYSTATE" VARCHAR2(1 BYTE) DEFAULT 'N',
	"EMAIL" VARCHAR2(100 BYTE),
	"PARKINGNAME" VARCHAR2(300 BYTE),
	"BOOKDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKINGBOOKMARK
--------------------------------------------------------

  CREATE TABLE "CAP"."PARKINGBOOKMARK"
   (	"EMAIL" VARCHAR2(100 BYTE),
	"PARKINGNAME" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKINGPAY
--------------------------------------------------------

  CREATE TABLE "CAP"."PARKINGPAY"
   (	"PAYID" VARCHAR2(100 BYTE),
	"PAYMETHOD" VARCHAR2(20 BYTE),
	"NAME" VARCHAR2(10 BYTE),
	"PRICE" NUMBER,
	"EMAIL" VARCHAR2(30 BYTE),
	"PARKINGNAME" VARCHAR2(300 BYTE),
	"PHONE" VARCHAR2(15 BYTE),
	"BOOKID" VARCHAR2(100 BYTE),
	"PAYDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table Q_BOARD
--------------------------------------------------------

  CREATE TABLE "CAP"."Q_BOARD"
   (	"BNO" NUMBER,
	"TITLE" VARCHAR2(100 BYTE),
	"CONTENT" VARCHAR2(1000 BYTE),
	"WRITER" VARCHAR2(50 BYTE),
	"REGDATE" DATE,
	"NOCOUNT" NUMBER,
	"NORECO" NUMBER,
	"MBO" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REGISTER
--------------------------------------------------------

  CREATE TABLE "CAP"."REGISTER"
   (	"EMAIL" VARCHAR2(100 BYTE),
	"REGISTERLICENCE" VARCHAR2(2000 BYTE),
	"ACCOUNTNUM" VARCHAR2(200 BYTE),
	"BANKNAME" VARCHAR2(200 BYTE),
	"REGDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESIDENCE
--------------------------------------------------------

  CREATE TABLE "CAP"."RESIDENCE"
   (	"RESNAME" VARCHAR2(300 BYTE),
	"POSTCODE" VARCHAR2(10 BYTE),
	"ROADADDRESS" VARCHAR2(300 BYTE),
	"JIBUNADDRESS" VARCHAR2(300 BYTE),
	"DETAILADDRESS" VARCHAR2(300 BYTE),
	"EXTRAADDRESS" VARCHAR2(300 BYTE),
	"LAT" NUMBER,
	"LNG" NUMBER,
	"REGDATE" TIMESTAMP (6),
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CAP.CS
SET DEFINE OFF;
Insert into CAP.CS (CHARGENAME,OPERATION,CHARGESPEED,CHARGEAMOUNT,MIN30FEE,ADDMIN10FEE,MANAGETIME,CHARGEPIC,APTMAP,CABLE,CHARGETYPE,REGDATE,CHARGINGCHK,RESNAME) values ('1','한국 전력','12','12','12','12','12','/img/upload/11.png','/img/upload/20.png','dcChademo','dcCombo',to_timestamp('20/08/11 15:34:42.000000000','RR/MM/DD HH24:MI:SSXFF'),'Y','x');
Insert into CAP.CS (CHARGENAME,OPERATION,CHARGESPEED,CHARGEAMOUNT,MIN30FEE,ADDMIN10FEE,MANAGETIME,CHARGEPIC,APTMAP,CABLE,CHARGETYPE,REGDATE,CHARGINGCHK,RESNAME) values ('xe','GS 칼텍스','1','1','1','1','1','/img/upload/20.png','/img/upload/28.png','dcCombo','dcCombo',to_timestamp('20/08/11 16:24:20.000000000','RR/MM/DD HH24:MI:SSXFF'),'Y','x');
Insert into CAP.CS (CHARGENAME,OPERATION,CHARGESPEED,CHARGEAMOUNT,MIN30FEE,ADDMIN10FEE,MANAGETIME,CHARGEPIC,APTMAP,CABLE,CHARGETYPE,REGDATE,CHARGINGCHK,RESNAME) values ('fd','GS 칼텍스','11','11','11','11',null,'/img/upload/17.png','/img/upload/19.png','dcCombo','dcCombo',to_timestamp('20/08/11 16:55:26.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.CS (CHARGENAME,OPERATION,CHARGESPEED,CHARGEAMOUNT,MIN30FEE,ADDMIN10FEE,MANAGETIME,CHARGEPIC,APTMAP,CABLE,CHARGETYPE,REGDATE,CHARGINGCHK,RESNAME) values ('rf','한국 전력','11','11','11','11','11','/img/upload/20.png','/img/upload/19.png','dcCombo','super',to_timestamp('20/08/11 16:59:24.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
REM INSERTING into CAP.GUARD
SET DEFINE OFF;
REM INSERTING into CAP.MEMBER
SET DEFINE OFF;
Insert into CAP.MEMBER (EMAIL,CREATED_DATE,MODIFIED_DATE,NAME,PASSWORD,PHONE,PICTURE,ROLE) values ('qw',to_timestamp('20/08/11 15:29:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null,'qw','qw','qw','/img/upload/1.png','관리자');
Insert into CAP.MEMBER (EMAIL,CREATED_DATE,MODIFIED_DATE,NAME,PASSWORD,PHONE,PICTURE,ROLE) values ('qwe',to_timestamp('20/08/11 15:29:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null,'qw','qw','qw','/img/upload/1.png','등록자');
Insert into CAP.MEMBER (EMAIL,CREATED_DATE,MODIFIED_DATE,NAME,PASSWORD,PHONE,PICTURE,ROLE) values ('qwer',to_timestamp('20/08/11 15:29:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null,'qw','qw','qw','/img/upload/1.png','일반');
REM INSERTING into CAP.PARKING
SET DEFINE OFF;
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('da','개인 사유지',33,33,33,'33','/img/upload/23.png','/img/upload/24.png',to_timestamp('20/08/11 17:02:45.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('rr','개인 사유지',11,11,11,'11','/img/upload/16.png','/img/upload/17.png',to_timestamp('20/08/11 17:03:33.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('22','개인 사유지',11,11,11,'11','/img/upload/19.png','/img/upload/12.png',to_timestamp('20/08/11 17:04:22.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('adf','개인 사유지',11,11,11,'1','/img/upload/8.png','/img/upload/7.png',to_timestamp('20/08/11 17:06:26.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('xf','개인 사유지',11,11,1,'11','/img/upload/54.png','/img/upload/60.jpg',to_timestamp('20/08/11 17:07:30.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('f','개인 사유지',11,1,11,'1','/img/upload/62.jpg','/img/upload/41.png',to_timestamp('20/08/11 17:08:22.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('45','개인 사유지',231,213,123,'213','/img/upload/21.png','/img/upload/55.png',to_timestamp('20/08/11 17:13:41.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('tt','개인 사유지',1,1,1,'1','/img/upload/10.png','/img/upload/9.png',to_timestamp('20/08/11 17:16:58.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
Insert into CAP.PARKING (PARKINGNAME,PARKINGTYPE,PLACE,MIN30FEE,ADDMIN10FEE,MANAGETIME,PARKINGPIC,APTMAP,REGDATE,PARKINGCHK,RESNAME) values ('TEST','개인 사유지',11,1,1,'11','/img/upload/3.png','/img/upload/4.png',to_timestamp('20/08/11 17:34:36.000000000','RR/MM/DD HH24:MI:SSXFF'),'N','x');
REM INSERTING into CAP.PARKINGBOOK
SET DEFINE OFF;
REM INSERTING into CAP.PARKINGBOOKMARK
SET DEFINE OFF;
REM INSERTING into CAP.PARKINGPAY
SET DEFINE OFF;
REM INSERTING into CAP.Q_BOARD
SET DEFINE OFF;
REM INSERTING into CAP.REGISTER
SET DEFINE OFF;
Insert into CAP.REGISTER (EMAIL,REGISTERLICENCE,ACCOUNTNUM,BANKNAME,REGDATE) values ('qwe','/img/upload/4.png','qw23','qw22',to_timestamp('20/08/11 15:30:24.000000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into CAP.RESIDENCE
SET DEFINE OFF;
Insert into CAP.RESIDENCE (RESNAME,POSTCODE,ROADADDRESS,JIBUNADDRESS,DETAILADDRESS,EXTRAADDRESS,LAT,LNG,REGDATE,EMAIL) values ('x','08758','서울 관악구 남부순환로 1817','서울 관악구 봉천동 861-6','q',' (봉천동)',37.482216983525895,126.95254188528692,to_timestamp('20/08/11 15:30:50.000000000','RR/MM/DD HH24:MI:SSXFF'),'qwe');
Insert into CAP.RESIDENCE (RESNAME,POSTCODE,ROADADDRESS,JIBUNADDRESS,DETAILADDRESS,EXTRAADDRESS,LAT,LNG,REGDATE,EMAIL) values ('11',null,null,null,null,null,null,null,to_timestamp('20/08/11 17:19:46.000000000','RR/MM/DD HH24:MI:SSXFF'),'qwe');
--------------------------------------------------------
--  DDL for Index CS_CHARGENAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."CS_CHARGENAME_PK" ON "CAP"."CS" ("CHARGENAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GUARD_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."GUARD_EMAIL_PK" ON "CAP"."GUARD" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007060
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."SYS_C007060" ON "CAP"."MEMBER" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARKING_PARKINGNAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."PARKING_PARKINGNAME_PK" ON "CAP"."PARKING" ("PARKINGNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARKINGBOOK_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."PARKINGBOOK_ID_PK" ON "CAP"."PARKINGBOOK" ("BOOKID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PBOOKMARK_EMAIL_PARKINGNAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."PBOOKMARK_EMAIL_PARKINGNAME_PK" ON "CAP"."PARKINGBOOKMARK" ("EMAIL", "PARKINGNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARKINGPAY_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."PARKINGPAY_ID_PK" ON "CAP"."PARKINGPAY" ("PAYID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index Q_BOARD_BNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."Q_BOARD_BNO_PK" ON "CAP"."Q_BOARD" ("BNO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REGISTER_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."REGISTER_EMAIL_PK" ON "CAP"."REGISTER" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESIDENCE_RESNAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAP"."RESIDENCE_RESNAME_PK" ON "CAP"."RESIDENCE" ("RESNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CS
--------------------------------------------------------

  ALTER TABLE "CAP"."CS" ADD CONSTRAINT "CS_CHARGENAME_PK" PRIMARY KEY ("CHARGENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAP"."CS" ADD CONSTRAINT "CS_CHARGINGCHK_CK" CHECK (chargingChk in('Y', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table GUARD
--------------------------------------------------------

  ALTER TABLE "CAP"."GUARD" ADD CONSTRAINT "GUARD_EMAIL_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "CAP"."MEMBER" ADD PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAP"."MEMBER" MODIFY ("ROLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARKING
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKING" ADD CONSTRAINT "PARKING_PARKINGNAME_PK" PRIMARY KEY ("PARKINGNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAP"."PARKING" ADD CONSTRAINT "PARKING_PARKINGCHK_CK" CHECK (parkingChk in('Y', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table PARKINGBOOK
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKINGBOOK" ADD CONSTRAINT "PARKINGBOOK_ID_PK" PRIMARY KEY ("BOOKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARKINGBOOKMARK
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKINGBOOKMARK" ADD CONSTRAINT "PBOOKMARK_EMAIL_PARKINGNAME_PK" PRIMARY KEY ("EMAIL", "PARKINGNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARKINGPAY
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKINGPAY" ADD CONSTRAINT "PARKINGPAY_ID_PK" PRIMARY KEY ("PAYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Q_BOARD
--------------------------------------------------------

  ALTER TABLE "CAP"."Q_BOARD" ADD CONSTRAINT "Q_BOARD_BNO_PK" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAP"."Q_BOARD" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "CAP"."Q_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CAP"."Q_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CAP"."Q_BOARD" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTER
--------------------------------------------------------

  ALTER TABLE "CAP"."REGISTER" ADD CONSTRAINT "REGISTER_EMAIL_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESIDENCE
--------------------------------------------------------

  ALTER TABLE "CAP"."RESIDENCE" ADD CONSTRAINT "RESIDENCE_RESNAME_PK" PRIMARY KEY ("RESNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CS
--------------------------------------------------------

  ALTER TABLE "CAP"."CS" ADD CONSTRAINT "CS_RESNAME_FK" FOREIGN KEY ("RESNAME")
	  REFERENCES "CAP"."RESIDENCE" ("RESNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GUARD
--------------------------------------------------------

  ALTER TABLE "CAP"."GUARD" ADD CONSTRAINT "GUARD_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "CAP"."MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CAP"."GUARD" ADD CONSTRAINT "GURAD_RESNAME_FK" FOREIGN KEY ("RESNAME")
	  REFERENCES "CAP"."RESIDENCE" ("RESNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKING
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKING" ADD CONSTRAINT "PARKING_RESNAME_FK" FOREIGN KEY ("RESNAME")
	  REFERENCES "CAP"."RESIDENCE" ("RESNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKINGBOOK
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKINGBOOK" ADD CONSTRAINT "PARKINGBOOK_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "CAP"."MEMBER" ("EMAIL") ENABLE;
  ALTER TABLE "CAP"."PARKINGBOOK" ADD CONSTRAINT "PARKINGBOOK_PARKINGNAME_FK" FOREIGN KEY ("PARKINGNAME")
	  REFERENCES "CAP"."PARKING" ("PARKINGNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKINGBOOKMARK
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKINGBOOKMARK" ADD CONSTRAINT "PBOOKMARK_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "CAP"."MEMBER" ("EMAIL") ENABLE;
  ALTER TABLE "CAP"."PARKINGBOOKMARK" ADD CONSTRAINT "PBOOKMARK_PARKINGNAME_FK" FOREIGN KEY ("PARKINGNAME")
	  REFERENCES "CAP"."PARKING" ("PARKINGNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKINGPAY
--------------------------------------------------------

  ALTER TABLE "CAP"."PARKINGPAY" ADD CONSTRAINT "PARKINGPAY_BOOKID_FK" FOREIGN KEY ("BOOKID")
	  REFERENCES "CAP"."PARKINGBOOK" ("BOOKID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTER
--------------------------------------------------------

  ALTER TABLE "CAP"."REGISTER" ADD CONSTRAINT "REGISTER_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "CAP"."MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESIDENCE
--------------------------------------------------------

  ALTER TABLE "CAP"."RESIDENCE" ADD CONSTRAINT "RESIDENCE_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "CAP"."REGISTER" ("EMAIL") ON DELETE CASCADE ENABLE;
